language: java
sudo: true
notifications:
  email: false
before_install:
  - pwd
  - cd /home/travis/build/pierreDebuisson/ColecticaSwaggerExamples/Java/JavaSwaggerApiInseeGraddle/
  - gradle assemble
  - cd /home/travis/build/pierreDebuisson/ColecticaSwaggerExamples/Java/JavaSwaggerApiInseeGraddle/
  - chmod 777 gradlew

