/* 
 * Colectica Repository REST API
 *
 * Colectica Repository REST API
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace Colectica.RestClientV1.Model
{
    /// <summary>
    /// InternationalIdentifier
    /// </summary>
    [DataContract]
    public partial class InternationalIdentifier :  IEquatable<InternationalIdentifier>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="InternationalIdentifier" /> class.
        /// </summary>
        /// <param name="ManagingAgency">ManagingAgency.</param>
        /// <param name="Identifier">Identifier.</param>
        public InternationalIdentifier(CodeValue ManagingAgency = default(CodeValue), string Identifier = default(string))
        {
            this.ManagingAgency = ManagingAgency;
            this.Identifier = Identifier;
        }
        
        /// <summary>
        /// Gets or Sets ManagingAgency
        /// </summary>
        [DataMember(Name="ManagingAgency", EmitDefaultValue=false)]
        public CodeValue ManagingAgency { get; set; }
        /// <summary>
        /// Gets or Sets Identifier
        /// </summary>
        [DataMember(Name="Identifier", EmitDefaultValue=false)]
        public string Identifier { get; set; }
        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InternationalIdentifier {\n");
            sb.Append("  ManagingAgency: ").Append(ManagingAgency).Append("\n");
            sb.Append("  Identifier: ").Append(Identifier).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            return this.Equals(obj as InternationalIdentifier);
        }

        /// <summary>
        /// Returns true if InternationalIdentifier instances are equal
        /// </summary>
        /// <param name="other">Instance of InternationalIdentifier to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InternationalIdentifier other)
        {
            // credit: http://stackoverflow.com/a/10454552/677735
            if (other == null)
                return false;

            return 
                (
                    this.ManagingAgency == other.ManagingAgency ||
                    this.ManagingAgency != null &&
                    this.ManagingAgency.Equals(other.ManagingAgency)
                ) && 
                (
                    this.Identifier == other.Identifier ||
                    this.Identifier != null &&
                    this.Identifier.Equals(other.Identifier)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            // credit: http://stackoverflow.com/a/263416/677735
            unchecked // Overflow is fine, just wrap
            {
                int hash = 41;
                // Suitable nullity checks etc, of course :)
                if (this.ManagingAgency != null)
                    hash = hash * 59 + this.ManagingAgency.GetHashCode();
                if (this.Identifier != null)
                    hash = hash * 59 + this.Identifier.GetHashCode();
                return hash;
            }
        }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        { 
            yield break;
        }
    }

}
