/*
 * Colectica Repository REST API
 * Colectica Repository REST API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * CodeValue
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-17T15:59:17.406-05:00")
public class CodeValue {
  @SerializedName("Value")
  private String value = null;

  @SerializedName("CodeListId")
  private String codeListId = null;

  @SerializedName("CodeListName")
  private String codeListName = null;

  @SerializedName("CodeListAgency")
  private String codeListAgency = null;

  @SerializedName("CodeListVersion")
  private String codeListVersion = null;

  @SerializedName("OtherValue")
  private String otherValue = null;

  @SerializedName("CodeListUrn")
  private String codeListUrn = null;

  public CodeValue value(String value) {
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value
  **/
  @ApiModelProperty(value = "")
  public String getValue() {
    return value;
  }

  public void setValue(String value) {
    this.value = value;
  }

  public CodeValue codeListId(String codeListId) {
    this.codeListId = codeListId;
    return this;
  }

   /**
   * Get codeListId
   * @return codeListId
  **/
  @ApiModelProperty(value = "")
  public String getCodeListId() {
    return codeListId;
  }

  public void setCodeListId(String codeListId) {
    this.codeListId = codeListId;
  }

  public CodeValue codeListName(String codeListName) {
    this.codeListName = codeListName;
    return this;
  }

   /**
   * Get codeListName
   * @return codeListName
  **/
  @ApiModelProperty(value = "")
  public String getCodeListName() {
    return codeListName;
  }

  public void setCodeListName(String codeListName) {
    this.codeListName = codeListName;
  }

  public CodeValue codeListAgency(String codeListAgency) {
    this.codeListAgency = codeListAgency;
    return this;
  }

   /**
   * Get codeListAgency
   * @return codeListAgency
  **/
  @ApiModelProperty(value = "")
  public String getCodeListAgency() {
    return codeListAgency;
  }

  public void setCodeListAgency(String codeListAgency) {
    this.codeListAgency = codeListAgency;
  }

  public CodeValue codeListVersion(String codeListVersion) {
    this.codeListVersion = codeListVersion;
    return this;
  }

   /**
   * Get codeListVersion
   * @return codeListVersion
  **/
  @ApiModelProperty(value = "")
  public String getCodeListVersion() {
    return codeListVersion;
  }

  public void setCodeListVersion(String codeListVersion) {
    this.codeListVersion = codeListVersion;
  }

  public CodeValue otherValue(String otherValue) {
    this.otherValue = otherValue;
    return this;
  }

   /**
   * Get otherValue
   * @return otherValue
  **/
  @ApiModelProperty(value = "")
  public String getOtherValue() {
    return otherValue;
  }

  public void setOtherValue(String otherValue) {
    this.otherValue = otherValue;
  }

  public CodeValue codeListUrn(String codeListUrn) {
    this.codeListUrn = codeListUrn;
    return this;
  }

   /**
   * Get codeListUrn
   * @return codeListUrn
  **/
  @ApiModelProperty(value = "")
  public String getCodeListUrn() {
    return codeListUrn;
  }

  public void setCodeListUrn(String codeListUrn) {
    this.codeListUrn = codeListUrn;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CodeValue codeValue = (CodeValue) o;
    return Objects.equals(this.value, codeValue.value) &&
        Objects.equals(this.codeListId, codeValue.codeListId) &&
        Objects.equals(this.codeListName, codeValue.codeListName) &&
        Objects.equals(this.codeListAgency, codeValue.codeListAgency) &&
        Objects.equals(this.codeListVersion, codeValue.codeListVersion) &&
        Objects.equals(this.otherValue, codeValue.otherValue) &&
        Objects.equals(this.codeListUrn, codeValue.codeListUrn);
  }

  @Override
  public int hashCode() {
    return Objects.hash(value, codeListId, codeListName, codeListAgency, codeListVersion, otherValue, codeListUrn);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CodeValue {\n");
    
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    codeListId: ").append(toIndentedString(codeListId)).append("\n");
    sb.append("    codeListName: ").append(toIndentedString(codeListName)).append("\n");
    sb.append("    codeListAgency: ").append(toIndentedString(codeListAgency)).append("\n");
    sb.append("    codeListVersion: ").append(toIndentedString(codeListVersion)).append("\n");
    sb.append("    otherValue: ").append(toIndentedString(otherValue)).append("\n");
    sb.append("    codeListUrn: ").append(toIndentedString(codeListUrn)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

