/*
 * Colectica Repository REST API
 * Colectica Repository REST API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * CommitOptions
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-17T15:59:17.406-05:00")
public class CommitOptions {
  @SerializedName("VersionRationale")
  private Map<String, String> versionRationale = null;

  @SerializedName("SetName")
  private String setName = null;

  public CommitOptions versionRationale(Map<String, String> versionRationale) {
    this.versionRationale = versionRationale;
    return this;
  }

  public CommitOptions putVersionRationaleItem(String key, String versionRationaleItem) {
    if (this.versionRationale == null) {
      this.versionRationale = new HashMap<String, String>();
    }
    this.versionRationale.put(key, versionRationaleItem);
    return this;
  }

   /**
   * Get versionRationale
   * @return versionRationale
  **/
  @ApiModelProperty(value = "")
  public Map<String, String> getVersionRationale() {
    return versionRationale;
  }

  public void setVersionRationale(Map<String, String> versionRationale) {
    this.versionRationale = versionRationale;
  }

  public CommitOptions setName(String setName) {
    this.setName = setName;
    return this;
  }

   /**
   * Get setName
   * @return setName
  **/
  @ApiModelProperty(value = "")
  public String getSetName() {
    return setName;
  }

  public void setSetName(String setName) {
    this.setName = setName;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CommitOptions commitOptions = (CommitOptions) o;
    return Objects.equals(this.versionRationale, commitOptions.versionRationale) &&
        Objects.equals(this.setName, commitOptions.setName);
  }

  @Override
  public int hashCode() {
    return Objects.hash(versionRationale, setName);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CommitOptions {\n");
    
    sb.append("    versionRationale: ").append(toIndentedString(versionRationale)).append("\n");
    sb.append("    setName: ").append(toIndentedString(setName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

