/*
 * Colectica Repository REST API
 * Colectica Repository REST API
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.UUID;

/**
 * IdentifierTriple
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-08-17T15:59:17.406-05:00")
public class IdentifierTriple {
  @SerializedName("Item1")
  private UUID item1 = null;

  @SerializedName("Item2")
  private Long item2 = null;

  @SerializedName("Item3")
  private String item3 = null;

   /**
   * Get item1
   * @return item1
  **/
  @ApiModelProperty(value = "")
  public UUID getItem1() {
    return item1;
  }

   /**
   * Get item2
   * @return item2
  **/
  @ApiModelProperty(value = "")
  public Long getItem2() {
    return item2;
  }

   /**
   * Get item3
   * @return item3
  **/
  @ApiModelProperty(value = "")
  public String getItem3() {
    return item3;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    IdentifierTriple identifierTriple = (IdentifierTriple) o;
    return Objects.equals(this.item1, identifierTriple.item1) &&
        Objects.equals(this.item2, identifierTriple.item2) &&
        Objects.equals(this.item3, identifierTriple.item3);
  }

  @Override
  public int hashCode() {
    return Objects.hash(item1, item2, item3);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class IdentifierTriple {\n");
    
    sb.append("    item1: ").append(toIndentedString(item1)).append("\n");
    sb.append("    item2: ").append(toIndentedString(item2)).append("\n");
    sb.append("    item3: ").append(toIndentedString(item3)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

